default: &default
  host: localhost
  port: 6379
  password: flamehaze
  timeout: 5000
  expire_after: 604800

development:
  <<: *default
  db: 15

test:
  <<: *default
  db: 15

integration:
  <<: *default
  db: 15

staging:
  <<: *default
  db: 15

